client_config_backend: settings
client_config:
  client_id: 585977834243-i7qdks6o2ofuh9kb3pv4mobjaq14b6qr.apps.googleusercontent.com
  client_secret: bTW6LvWDT0HhJqTtrenDQgj0

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install